#pragma once

// From glfw3.h
#define KAME_MOUSE_BUTTON_1         0
#define KAME_MOUSE_BUTTON_2         1
#define KAME_MOUSE_BUTTON_3         2
#define KAME_MOUSE_BUTTON_4         3
#define KAME_MOUSE_BUTTON_5         4
#define KAME_MOUSE_BUTTON_6         5
#define KAME_MOUSE_BUTTON_7         6
#define KAME_MOUSE_BUTTON_8         7
#define KAME_MOUSE_BUTTON_LAST      KAME_MOUSE_BUTTON_8
#define KAME_MOUSE_BUTTON_LEFT      KAME_MOUSE_BUTTON_1
#define KAME_MOUSE_BUTTON_RIGHT     KAME_MOUSE_BUTTON_2
#define KAME_MOUSE_BUTTON_MIDDLE    KAME_MOUSE_BUTTON_3